- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      command: "/etc/init.d/clickhouse-server start"
  tasks:
    - block:
      - name: Add repository
        yum_repository:
          name: clickhouse
          description: clickhouse repo
          baseurl: https://packages.clickhouse.com/rpm/stable/
          gpgkey: https://packages.clickhouse.com/rpm/stable/repodata/repomd.xml.key
          gpgcheck: false
      - name: Install clickhouse
        ansible.builtin.yum:
          name:
            - clickhouse-server
            - clickhouse-client
          state: latest
      - name: Enable service clickhouse-server
        ansible.builtin.systemd:
          name: clickhouse-server
          enabled: true
          masked: no
      - name: Start clickhouse-server
        command: "/etc/init.d/clickhouse-server start"
      - name: Create database
        command: "clickhouse-client -q 'create database logs;'"
        register: create_db
        failed_when: create_db.rc != 0 and create_db.rc !=82
        changed_when: create_db.rc == 0
- name: Install Vector
  hosts: vector
  handlers:
    - name: Start vector
      become: true
      ansible.builtin.shell: "vector --config {{ vector_path }}/config/vector.toml"
  tasks:
    - block:
      - name: Get vector distrib
        ansible.builtin.get_url:
          url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-x86_64-unknown-linux-gnu.tar.gz"
          force: true
          dest: "/tmp/vector.tar.gz"
          mode: 0755
      - name: Create dir
        become: true
        file:
          state: directory
          path: "{{ vector_path }}"
          mode: 0755
      - name: Unarchive vector
        become: true
        unarchive:
          copy: false
          src: "/tmp/vector.tar.gz"
          dest: "{{ vector_path }}"
          extra_opts: [--strip-components=2]
          creates: "{{ vector_path }}/bin/vector"
      - name: Copy vector bin
        copy:
          src: "{{ vector_path }}/bin/vector"
          dest: "/usr/bin/"
          mode: 0755
          remote_src: yes
      - name: Copy service file
        copy:
          src: "{{ vector_path }}/etc/systemd/vector.service"
          dest: "/etc/systemd/system/"
          remote_src: yes
      - name: Create data dir
        become: true
        file:
          state: directory
          path: "{{ vector_data_dir }}"
          mode: 0755
