{
 "title": "New dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Disk Space Avalible",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{mountpoint='/'}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load averege",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "node_load1", "legendFormat": "1 min" },
    { "expr": "node_load5", "legendFormat": "5 min" },
    { "expr": "node_load15", "legendFormat": "15 min" }
   ]
  },
  {
   "title": "CPU util node",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{mode=\"idle\"}[30s])) * 100)",
     "legendFormat": "CPU Util"
    }
   ]
  },
  {
   "title": "Free memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "node_memory_MemFree_bytes", "legendFormat": "Free memory" }
   ]
  }
 ]
}