apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymente2
  labels:
    app: nginxe2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginxe2
  template:
    metadata:
      labels:
        app: nginxe2
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
      initContainers:
        - name: initservice
          image: busybox:latest
          command: ['sh', '-c', 'until nslookup servicee2.default.svc.cluster.local; do echo waiting for startin service; sleep 3s; done;']
---
apiVersion: v1
kind: Service
metadata:
  name: servicee2
spec:
  selector:
    app.kubernetes.io/name: nginxe2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
