---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymente1
  labels:
    app: nginxplusmultitule1
spec:
  replicas: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: nginxplusmultitule1
  template:
    metadata:
      labels:
        app: nginxplusmultitule1
    spec:
      containers:
      - name: nginx
        image: nginx:1.19
        ports:
        - containerPort: 80
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: http-port
---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  ports:
    - name: web
      port: 8001
      targetPort: 80
    - name: multitool
      port: 8081
      targetPort: 8080
  selector:
    app: nginxplusmultitule1
