- name: Install Clickhouse
  tags: clickhouse
  hosts: clickhouse
  roles:
    - clickhouse
- name: Install Vector
  tags: vector
  hosts: vector
  roles:
    - vector-role
  vars_files:
    - vars/vectorconfig.yml
- name: Install Lighthouse
  tags: lighthouse
  hosts: lighthouse
  roles:
    - lighthouse-role
