---
all:
  hosts:
    nexus-01:
#      ansible_host: <nexushost>
      ansible_connection: docker
  children:
    nexus:
      hosts:
        nexus-01:
  vars:
#    ansible_connection_type: paramiko
    ansible_user: root
