all:
  hosts: 
    nexus-01:
      ansible_host: 158.160.40.137
    sonar-01:
      ansible_host: 51.250.10.37
  children:
    nexus:
      hosts:
        nexus-01:
    sonarqube:
      hosts:
        sonar-01: 
    postgres:
      hosts:
        sonar-01:
  vars:
    ansible_user: centos
    ansible_connection_type: paramiko
