apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymente3
  labels:
    app: nginxplusmultitule1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginxplusmultitule1
  template:
    metadata:
      labels:
        app: nginxplusmultitule1
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          name: nginxport
      - name: multitool
        image: wbitt/network-multitool
        env:
        - name: HTTP_PORT
          value: "8080"
        ports:
        - containerPort: 8080
          name: multitoolport
---
apiVersion: v1
kind: Service
metadata:
  name: servicee3
spec:
  selector:
    app: nginxplusmultitule1
  ports:
    - name: porttonginx
      protocol: TCP
      port: 9001
      targetPort: 80
    - name: porttomultitool
      protocol: TCP
      port: 9002
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: servicenode1
spec:
  selector:
    app: nginxplusmultitule1
  type: NodePort
  ports:
    - name: porttonginx
      protocol: TCP
      port: 9001
      targetPort: 80
      nodePort: 31001
---
apiVersion: v1
kind: Pod
metadata:
  name: multitoolpode1
  labels:
    app: multitoolpode1 
spec:
  containers:
  - name: multitoolpode1
    image: wbitt/network-multitool
    env:
    - name: HTTP_PORT
      value: "8083"
    ports:
    - containerPort: 8083
