stages:
  - build_deploy

image: docker:20.10.5
  
services:
  - docker:20.10.5-dind

builder:
  stage: build_deploy
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  variables:
    DOCKER_IMAGE_NAME: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  
  script:
    - docker build -t registry.gitlab.com/v507-net/09-ci-06/hello:gitlab-$CI_COMMIT_SHORT_SHA .
    - docker push registry.gitlab.com/v507-net/09-ci-06/hello:gitlab-$CI_COMMIT_SHORT_SHA 
  rules:
    - if: $CI_COMMIT_BRANCH
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      exists:
        - Dockerfile
        